# Generated by Django 3.2.6 on 2021-08-25 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_auto_20210825_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='ad_id',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
