# Generated by Django 3.2.6 on 2021-08-27 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_ad_ad_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='cta',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='links',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='media_urls',
        ),
        migrations.AddField(
            model_name='ad',
            name='ad_body',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ad',
            name='ad_info',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
